# Generated by Django 4.2.8 on 2023-12-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecture_programs",
            name="lectures",
        ),
        migrations.AddField(
            model_name="lecture",
            name="program",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lectures",
                to="education.lecture_programs",
            ),
            preserve_default=False,
        ),
    ]
