# Generated by Django 4.2.8 on 2023-12-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0002_remove_lecture_programs_lectures_lecture_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture_programs",
            name="video",
            field=models.FileField(default=1, upload_to="lectures/videos/"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Lecture",
        ),
    ]
