# Generated by Django 4.2.8 on 2024-01-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0004_remove_lecture_programs_video_lecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture_programs",
            name="image",
            field=models.ImageField(
                default="default_image.jpg", upload_to="lecture_programs/images/"
            ),
        ),
    ]
