# Generated by Django 4.2.8 on 2023-12-19 07:16

import CourseIntro.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CourseIntro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseintro",
            name="image",
            field=CourseIntro.models.ResizedImageField(upload_to="course_intros/"),
        ),
        migrations.AlterField(
            model_name="courseintro",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
