# Generated by Django 4.2.8 on 2023-12-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("video", models.FileField(upload_to="lectures/videos/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Lecture_Programs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "lectures",
                    models.ManyToManyField(
                        related_name="included_in_programs", to="education.lecture"
                    ),
                ),
            ],
        ),
    ]
