# Generated by Django 4.2.8 on 2023-12-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0003_lecture_programs_video_delete_lecture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecture_programs",
            name="video",
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("video", models.FileField(upload_to="lectures/videos/")),
                ("description", models.TextField()),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="education.lecture_programs",
                    ),
                ),
            ],
        ),
    ]
