# Generated by Django 4.2.8 on 2024-01-02 05:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_alter_board_name"),
        ("board", "0008_alter_question_author"),
    ]

    operations = []
