# Generated by Django 4.2.8 on 2024-01-03 00:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0009_merge_20240102_1411"),
        ("board", "0009_merge_20240103_0230"),
    ]

    operations = []
