# Generated by Django 4.2.8 on 2023-12-19 04:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_video"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Video",
        ),
    ]
